project:
  type: website
  output-dir: docs

website:
  title: "Mel Baldino"
  navbar:
    left:
      - href: currentwork.qmd
        text: Current Research
      # - publications.qmd
      - href: pastwork.qmd
        text: Past Research
      - href: teaching.qmd
        text: Teaching
      - href: portfolio.qmd
        text: Portfolio
  page-footer: 
    left: "Last updated May 2024" 
    right: 
      - icon: mailbox 
        href: "mailto:melbaldino@berkeley.edu"
    

format:
  html:
    theme: cosmo # flatly, yeti, solar, litera, 
    embed-resources: true
    css: styles.css
    toc: true

editor: visual

